//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO_Practice
{
    using System;
    using System.Collections.Generic;
    
    public partial class COrder
    {
        public int OrderId { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> AddressId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
    }
}
